pipeline {
  agent any
  stages {
	  stage('Start') {
  		steps {
			step {
				sh 'echo id && ls && pwd'
			}
      }
  	}
  	stage('end') {
  		steps {
        	step {
				sh 'echo id && ls && pwd'
			}
       }
   	}
  }
}
